name: Build Docker image and push to server on new version tag

on:
  push:
    tags:
      - "*.*.*"

jobs:
  # lint-and-test:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [10.x, 12.x]

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - run: yarn lint
  #     - run: yarn test
  build-and-push:
    # needs: lint-and-test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          registry: ${{ secrets.DOCKER_HOST }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_REPOSITORY }}
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true
